/*
Use an immediate assertion to test the behavior of the adder for 10 random stimuli generated by TB. 
Use the design and TB code mentioned in the instructions tab.
*/
module adder(
  input      [3:0] a,b,
  output reg [4:0] s
);
  
  
  always@(*)
    begin
      s = a + b;
    end
 
  
endmodule

module tb;
  
  reg [3:0] a, b;
  wire [4:0] s;
  
  adder dut (a, b, s);
  
  initial begin
    for(int i = 0; i < 10; i++) begin
      a = $urandom;
      b = $urandom;
      #10;
    end   
  end
  
  
   initial begin
    $dumpfile("dump.vcd"); 
    $dumpvars;
    $assertvacuousoff(0);
    #110;
    $finish();
  end

  always @(*)
  begin
    A1: assert final (s == a + b) $info("Assertion Passed. a = %0d, b = %0d, s = %0d", a,b,s); else $error("[Error]: Assertion Failed at time: %0d. a = %0d, b = %0d, s = %0d", $time, a,b,s);
  end
  
  
endmodule